---
abstract: 'Include the Math::Int64 C client API in your distribution'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: '0.3601'
  Path::Class: '0.26'
  Test::More: '0.94'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.021, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-MathInt64
no_index:
  directory:
    - corpus
requires:
  Dist::Zilla: '0'
  ExtUtils::Typemaps: '0'
  File::ShareDir: '0'
  Moose: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/plicease/Dist-Zilla-Plugin-MathInt64/issues
  homepage: http://perl.wdlabs.com/Dist-Zilla-Plugin-MathInt64
  repository: git://github.com/plicease/Dist-Zilla-Plugin-MathInt64.git
version: '0.07'
